// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: ui_code

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_homepage
void ui_homepage_screen_init(void);
lv_obj_t * ui_homepage;
lv_obj_t * ui_homepagePanel;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_tempBar;
lv_obj_t * ui_humidityBar;
lv_obj_t * ui_temp;
lv_obj_t * ui_humidity;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_hour;
lv_obj_t * ui_Label7;
lv_obj_t * ui_min;
lv_obj_t * ui_month;
lv_obj_t * ui_Label10;
lv_obj_t * ui_day;
lv_obj_t * ui_year;
lv_obj_t * ui_airtempArc;
lv_obj_t * ui_Label13;
lv_obj_t * ui_airtemp;
lv_obj_t * ui_weather;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label15;
void ui_event_Button7(lv_event_t * e);
lv_obj_t * ui_Button7;
lv_obj_t * ui_Label28;
lv_obj_t * ui_Label33;

// SCREEN: ui_loadpage
void ui_loadpage_screen_init(void);
lv_obj_t * ui_loadpage;
lv_obj_t * ui_loadpagePanel;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_Label12;

// SCREEN: ui_menupage
void ui_menupage_screen_init(void);
lv_obj_t * ui_menupage;
lv_obj_t * ui_menupagepanel;
lv_obj_t * ui_humidifierSwitch;
lv_obj_t * ui_lampSwitch;
lv_obj_t * ui_humidifier;
lv_obj_t * ui_lamp;
void ui_event_Button2(lv_event_t * e);
lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
void ui_event_Button4(lv_event_t * e);
lv_obj_t * ui_Button4;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label9;
lv_obj_t * ui_backlinght;
lv_obj_t * ui_backlinghtSlider;
void ui_event_Button8(lv_event_t * e);
lv_obj_t * ui_Button8;
lv_obj_t * ui_Label32;

// SCREEN: ui_clockpage
void ui_clockpage_screen_init(void);
lv_obj_t * ui_clockpage;
lv_obj_t * ui_clockpagePanel;
lv_obj_t * ui_Label18;
lv_obj_t * ui_hourH;
lv_obj_t * ui_hourL;
lv_obj_t * ui_minL;
lv_obj_t * ui_minH;
lv_obj_t * ui_setButton;
lv_obj_t * ui_Label19;
lv_obj_t * ui_resetButton;
lv_obj_t * ui_Label20;
void ui_event_returnclock(lv_event_t * e);
lv_obj_t * ui_returnclock;
lv_obj_t * ui_Label22;
lv_obj_t * ui_Label23;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label29;
lv_obj_t * ui_Label30;
lv_obj_t * ui_Label31;

// SCREEN: ui_WiFipage
void ui_WiFipage_screen_init(void);
lv_obj_t * ui_WiFipage;
lv_obj_t * ui_WiFipagepanel;
void ui_event_returnWiFi(lv_event_t * e);
lv_obj_t * ui_returnWiFi;
lv_obj_t * ui_Label24;
lv_obj_t * ui_Label26;
lv_obj_t * ui_Label27;
void ui_event_TextArea1(lv_event_t * e);
lv_obj_t * ui_TextArea1;
void ui_event_TextArea2(lv_event_t * e);
lv_obj_t * ui_TextArea2;
lv_obj_t * ui_Keyboard3;

// SCREEN: ui_datapage
void ui_datapage_screen_init(void);
lv_obj_t * ui_datapage;
lv_obj_t * ui_datapagePanel;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Chart1;
lv_obj_t * ui_Label4;

// SCREEN: ui_Alarmevent
void ui_Alarmevent_screen_init(void);
lv_obj_t * ui_Alarmevent;
lv_obj_t * ui_AlarmeventPanel;
void ui_event_Button5(lv_event_t * e);
lv_obj_t * ui_Button5;
lv_obj_t * ui_Label16;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Label21;
lv_obj_t * ui_Button6;
lv_obj_t * ui_Label25;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
// #if LV_COLOR_16_SWAP !=0
//     #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
// #endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_menupage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_menupage_screen_init);
    }
}
void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_datapage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_datapage_screen_init);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_clockpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_clockpage_screen_init);
    }
}
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WiFipage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_WiFipage_screen_init);
    }
}
void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_homepage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_homepage_screen_init);
    }
}
void ui_event_returnclock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_menupage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_menupage_screen_init);
    }
}
void ui_event_returnWiFi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_menupage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_menupage_screen_init);
    }
}
void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard3,  ui_TextArea1);
    }
}
void ui_event_TextArea2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard3,  ui_TextArea2);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_menupage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_menupage_screen_init);
    }
}
void ui_event_Button5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_clockpage, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_clockpage_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_homepage_screen_init();
    ui_loadpage_screen_init();
    ui_menupage_screen_init();
    ui_clockpage_screen_init();
    ui_WiFipage_screen_init();
    ui_datapage_screen_init();
    ui_Alarmevent_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_homepage);
}
