// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: ui_code

#ifndef _UI_CODE_UI_H
#define _UI_CODE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl/lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_homepage
void ui_homepage_screen_init(void);
extern lv_obj_t * ui_homepage;
extern lv_obj_t * ui_homepagePanel;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_tempBar;
extern lv_obj_t * ui_humidityBar;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_humidity;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_hour;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_min;
extern lv_obj_t * ui_month;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_day;
extern lv_obj_t * ui_year;
extern lv_obj_t * ui_airtempArc;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_airtemp;
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label15;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label33;
// SCREEN: ui_loadpage
void ui_loadpage_screen_init(void);
extern lv_obj_t * ui_loadpage;
extern lv_obj_t * ui_loadpagePanel;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Label12;
// SCREEN: ui_menupage
void ui_menupage_screen_init(void);
extern lv_obj_t * ui_menupage;
extern lv_obj_t * ui_menupagepanel;
extern lv_obj_t * ui_humidifierSwitch;
extern lv_obj_t * ui_lampSwitch;
extern lv_obj_t * ui_humidifier;
extern lv_obj_t * ui_lamp;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_backlinght;
extern lv_obj_t * ui_backlinghtSlider;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label32;
// SCREEN: ui_clockpage
void ui_clockpage_screen_init(void);
extern lv_obj_t * ui_clockpage;
extern lv_obj_t * ui_clockpagePanel;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_hourH;
extern lv_obj_t * ui_hourL;
extern lv_obj_t * ui_minL;
extern lv_obj_t * ui_minH;
extern lv_obj_t * ui_setButton;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_resetButton;
extern lv_obj_t * ui_Label20;
void ui_event_returnclock(lv_event_t * e);
extern lv_obj_t * ui_returnclock;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_Label31;
// SCREEN: ui_WiFipage
void ui_WiFipage_screen_init(void);
extern lv_obj_t * ui_WiFipage;
extern lv_obj_t * ui_WiFipagepanel;
void ui_event_returnWiFi(lv_event_t * e);
extern lv_obj_t * ui_returnWiFi;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
void ui_event_TextArea2(lv_event_t * e);
extern lv_obj_t * ui_TextArea2;
extern lv_obj_t * ui_Keyboard3;
// SCREEN: ui_datapage
void ui_datapage_screen_init(void);
extern lv_obj_t * ui_datapage;
extern lv_obj_t * ui_datapagePanel;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_Alarmevent
void ui_Alarmevent_screen_init(void);
extern lv_obj_t * ui_Alarmevent;
extern lv_obj_t * ui_AlarmeventPanel;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui____initial_actions0;

LV_FONT_DECLARE(ui_font_airtemp);
LV_FONT_DECLARE(ui_font_alibaba14);
LV_FONT_DECLARE(ui_font_alibaba20);
LV_FONT_DECLARE(ui_font_backlight);
LV_FONT_DECLARE(ui_font_humidity);
LV_FONT_DECLARE(ui_font_return);
LV_FONT_DECLARE(ui_font_right);
LV_FONT_DECLARE(ui_font_temp);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
