// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: ui_code

#include "../ui.h"
lv_obj_t*ui_setButton;
lv_obj_t*ui_resetButton;

static void reset_set_enev(lv_event_t * e)
{
    lv_obj_t * tar = lv_event_get_target(e);
    if(tar==ui_resetButton)
    {
        lv_roller_set_selected(ui_hourH,0,LV_ANIM_ON);
        lv_roller_set_selected(ui_hourL,0,LV_ANIM_ON);
        lv_roller_set_selected(ui_minL,0,LV_ANIM_ON);
        lv_roller_set_selected(ui_minH,0,LV_ANIM_ON);
    }
    if(tar==ui_setButton)
    {
        char hourh,hourl,minh,minl;
        hourh = lv_roller_get_selected(ui_hourH);
        hourl = lv_roller_get_selected(ui_hourL);
        minh = lv_roller_get_selected(ui_minH);
        minl = lv_roller_get_selected(ui_minL);
        lv_label_set_text_fmt(ui_Label29,"%d%d",hourh,hourl);
        lv_label_set_text_fmt(ui_Label31,"%d%d",minh,minl);
    }
}
void ui_clockpage_screen_init(void)
{
    ui_clockpage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_clockpage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clockpage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clockpage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_clockpage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_clockpage, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clockpage, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_clockpage, lv_color_hex(0x000000), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_clockpagePanel = lv_obj_create(ui_clockpage);
    lv_obj_set_width(ui_clockpagePanel, 240);
    lv_obj_set_height(ui_clockpagePanel, 280);
    lv_obj_set_x(ui_clockpagePanel, 1);
    lv_obj_set_y(ui_clockpagePanel, 0);
    lv_obj_set_align(ui_clockpagePanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_clockpagePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_clockpagePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_clockpagePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_clockpagePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_clockpagePanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_clockpagePanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label18 = lv_label_create(ui_clockpage);
    lv_obj_set_width(ui_Label18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, 6);
    lv_obj_set_y(ui_Label18, -63);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, ":");
    lv_obj_set_style_text_color(ui_Label18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label18, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_hourH = lv_roller_create(ui_clockpage);
    lv_roller_set_options(ui_hourH, "0\n1\n2", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_hourH, 35);
    lv_obj_set_width(ui_hourH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_hourH, -66);
    lv_obj_set_y(ui_hourH, -60);
    lv_obj_set_align(ui_hourH, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_hourH, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_hourH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_hourH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_hourH, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hourH, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hourH, &lv_font_montserrat_20, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hourH, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hourH, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_hourL = lv_roller_create(ui_clockpage);
    lv_roller_set_options(ui_hourL, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9\n", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_hourL, 34);
    lv_obj_set_width(ui_hourL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_hourL, -26);
    lv_obj_set_y(ui_hourL, -60);
    lv_obj_set_align(ui_hourL, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_hourL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hourL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_hourL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_hourL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_hourL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_blend_mode(ui_hourL, LV_BLEND_MODE_NORMAL, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_opa(ui_hourL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_hourL, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_hourL, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_hourL, &lv_font_montserrat_20, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_hourL, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_hourL, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_minL = lv_roller_create(ui_clockpage);
    lv_roller_set_options(ui_minL, "0\n1\n2\n3\n4\n5\n6\n7\n8\n9", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_minL, 36);
    lv_obj_set_width(ui_minL, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_minL, 77);
    lv_obj_set_y(ui_minL, -60);
    lv_obj_set_align(ui_minL, LV_ALIGN_CENTER);
    lv_obj_set_style_border_color(ui_minL, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_minL, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_minL, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minL, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minL, &lv_font_montserrat_20, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_minL, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minL, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_minH = lv_roller_create(ui_clockpage);
    lv_roller_set_options(ui_minH, "0\n1\n2\n3\n4\n5", LV_ROLLER_MODE_NORMAL);
    lv_obj_set_height(ui_minH, 33);
    lv_obj_set_width(ui_minH, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_minH, 37);
    lv_obj_set_y(ui_minH, -60);
    lv_obj_set_align(ui_minH, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_minH, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_minH, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_minH, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_minH, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_minH, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_minH, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_minH, &lv_font_montserrat_20, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_minH, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_minH, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_setButton = lv_btn_create(ui_clockpage);
    lv_obj_set_width(ui_setButton, 47);
    lv_obj_set_height(ui_setButton, 27);
    lv_obj_set_x(ui_setButton, 47);
    lv_obj_set_y(ui_setButton, -16);
    lv_obj_set_align(ui_setButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_setButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_setButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_setButton, lv_color_hex(0x5B1EA2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_setButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_setButton,reset_set_enev,LV_EVENT_CLICKED,NULL);
    
    ui_Label19 = lv_label_create(ui_clockpage);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 47);
    lv_obj_set_y(ui_Label19, -14);
    lv_obj_set_align(ui_Label19, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label19, "设置");
    lv_obj_set_style_text_font(ui_Label19, &ui_font_alibaba20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_resetButton = lv_btn_create(ui_clockpage);
    lv_obj_set_width(ui_resetButton, 47);
    lv_obj_set_height(ui_resetButton, 27);
    lv_obj_set_x(ui_resetButton, -45);
    lv_obj_set_y(ui_resetButton, -16);
    lv_obj_set_align(ui_resetButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_resetButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_resetButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_resetButton, lv_color_hex(0x5B1EA2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_resetButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_resetButton, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_resetButton,reset_set_enev,LV_EVENT_CLICKED,NULL);

    ui_Label20 = lv_label_create(ui_clockpage);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, -44);
    lv_obj_set_y(ui_Label20, -14);
    lv_obj_set_align(ui_Label20, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label20, "清零");
    lv_obj_set_style_text_font(ui_Label20, &ui_font_alibaba20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_returnclock = lv_btn_create(ui_clockpage);
    lv_obj_set_width(ui_returnclock, 63);
    lv_obj_set_height(ui_returnclock, 32);
    lv_obj_set_x(ui_returnclock, 62);
    lv_obj_set_y(ui_returnclock, 77);
    lv_obj_set_align(ui_returnclock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_returnclock, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_returnclock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_returnclock, lv_color_hex(0x131510), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_returnclock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_returnclock, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_clockpage);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 61);
    lv_obj_set_y(ui_Label22, 77);
    lv_obj_set_align(ui_Label22, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label22, "");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_return, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_clockpage);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, -3);
    lv_obj_set_y(ui_Label23, -104);
    lv_obj_set_align(ui_Label23, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label23, "闹钟设置");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &ui_font_alibaba20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_clockpage);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, -65);
    lv_obj_set_y(ui_Label14, 32);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "闹钟:");
    lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_alibaba20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_clockpage);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, -20);
    lv_obj_set_y(ui_Label29, 32);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "0");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_clockpage);
    lv_obj_set_width(ui_Label30, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, -1);
    lv_obj_set_y(ui_Label30, 31);
    lv_obj_set_align(ui_Label30, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label30, ":");
    lv_obj_set_style_text_color(ui_Label30, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label30, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label31 = lv_label_create(ui_clockpage);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, 20);
    lv_obj_set_y(ui_Label31, 32);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "0");
    lv_obj_set_style_text_color(ui_Label31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label31, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_returnclock, ui_event_returnclock, LV_EVENT_ALL, NULL);

}
