// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.3
// Project name: ui_code

#include "../ui.h"
#include "peripheral.h"
lv_obj_t *ui_humidifierSwitch;
lv_obj_t *ui_lampSwitch;
lv_obj_t *ui_backlinghtSlider;
// extern lv_chart_series_t * ui_Chart1_series_1;
// extern lv_chart_series_t * ui_Chart1_series_2;
// uint16_t data_buff[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
static void set_enev(lv_event_t *e)
{
    lv_obj_t *tar = lv_event_get_target(e);
    if (tar == ui_humidifierSwitch)
    {
        if (lv_obj_has_state(ui_humidifierSwitch, LV_STATE_CHECKED)) // 判断是否是打开状态
        {
            humidifier_open();

        }
        else
        {
            humidifier_close();
        }
    }
    if (tar == ui_lampSwitch)
    {
        if (lv_obj_has_state(ui_lampSwitch, LV_STATE_CHECKED)) // 判断是否是打开状态
        {
            void lamp_on();
        }
        else
        {
            void lamp_off();
        }
    }
    if (tar == ui_backlinghtSlider)
    {
        char slider_value;
        slider_value = lv_slider_get_value(ui_backlinghtSlider);
        backlight_duty_set(slider_value);
    }
}
void ui_menupage_screen_init(void)
{
    ui_menupage = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_menupage, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_menupage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menupage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_menupage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_menupagepanel = lv_obj_create(ui_menupage);
    lv_obj_set_width(ui_menupagepanel, 240);
    lv_obj_set_height(ui_menupagepanel, 280);
    lv_obj_set_align(ui_menupagepanel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_menupagepanel, LV_OBJ_FLAG_SCROLLABLE); /// Flags
    lv_obj_set_style_bg_color(ui_menupagepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_menupagepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_menupagepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_menupagepanel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_menupagepanel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_humidifierSwitch = lv_switch_create(ui_menupage);
    lv_obj_set_width(ui_humidifierSwitch, 50);
    lv_obj_set_height(ui_humidifierSwitch, 25);
    lv_obj_set_x(ui_humidifierSwitch, -77);
    lv_obj_set_y(ui_humidifierSwitch, 62);
    lv_obj_set_align(ui_humidifierSwitch, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_humidifierSwitch, set_enev, LV_EVENT_CLICKED, NULL);

    ui_lampSwitch = lv_switch_create(ui_menupage);
    lv_obj_set_width(ui_lampSwitch, 50);
    lv_obj_set_height(ui_lampSwitch, 25);
    lv_obj_set_x(ui_lampSwitch, -5);
    lv_obj_set_y(ui_lampSwitch, 61);
    lv_obj_set_align(ui_lampSwitch, LV_ALIGN_CENTER);
    lv_obj_add_event_cb(ui_lampSwitch, set_enev, LV_EVENT_CLICKED, NULL);

    ui_humidifier = lv_label_create(ui_menupage);
    lv_obj_set_width(ui_humidifier, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_humidifier, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_humidifier, -77);
    lv_obj_set_y(ui_humidifier, 35);
    lv_obj_set_align(ui_humidifier, LV_ALIGN_CENTER);
    lv_label_set_text(ui_humidifier, "加湿器");
    lv_obj_set_style_text_color(ui_humidifier, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_humidifier, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_humidifier, &ui_font_alibaba14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_lamp = lv_label_create(ui_menupage);
    lv_obj_set_width(ui_lamp, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_lamp, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_lamp, -5);
    lv_obj_set_y(ui_lamp, 35);
    lv_obj_set_align(ui_lamp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lamp, "台灯");
    lv_obj_set_style_text_color(ui_lamp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lamp, &ui_font_alibaba14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_menupage);
    lv_obj_set_width(ui_Button2, 132);
    lv_obj_set_height(ui_Button2, 41);
    lv_obj_set_x(ui_Button2, -1);
    lv_obj_set_y(ui_Button2, -101);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x30ED4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_menupage);
    lv_obj_set_width(ui_Button3, 132);
    lv_obj_set_height(ui_Button3, 41);
    lv_obj_set_x(ui_Button3, -1);
    lv_obj_set_y(ui_Button3, -53);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xD3C22C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_btn_create(ui_menupage);
    lv_obj_set_width(ui_Button4, 132);
    lv_obj_set_height(ui_Button4, 41);
    lv_obj_set_x(ui_Button4, -1);
    lv_obj_set_y(ui_Button4, -6);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x2F5FDA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_menupage);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label6, -4);
    lv_obj_set_y(ui_Label6, -99);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "数据统计");
    lv_obj_set_style_text_font(ui_Label6, &ui_font_alibaba20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_menupage);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label8, -2);
    lv_obj_set_y(ui_Label8, -52);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "闹钟设置");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_alibaba20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_menupage);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, -4);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "WiFi连接");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_alibaba20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backlinght = lv_label_create(ui_menupage);
    lv_obj_set_width(ui_backlinght, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_backlinght, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_backlinght, -78);
    lv_obj_set_y(ui_backlinght, 100);
    lv_obj_set_align(ui_backlinght, LV_ALIGN_CENTER);
    lv_label_set_text(ui_backlinght, "");
    lv_obj_set_style_text_color(ui_backlinght, lv_color_hex(0x47D87E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_backlinght, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_backlinght, &ui_font_backlight, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backlinghtSlider = lv_slider_create(ui_menupage);
    lv_slider_set_value(ui_backlinghtSlider, 50, LV_ANIM_OFF);
    if (lv_slider_get_mode(ui_backlinghtSlider) == LV_SLIDER_MODE_RANGE)
        lv_slider_set_left_value(ui_backlinghtSlider, 0,
                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_backlinghtSlider, 144);
    lv_obj_set_height(ui_backlinghtSlider, 10);
    lv_obj_set_x(ui_backlinghtSlider, 11);
    lv_obj_set_y(ui_backlinghtSlider, 101);
    lv_obj_set_align(ui_backlinghtSlider, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_backlinghtSlider, lv_color_hex(0xB0EF59), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_backlinghtSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_backlinghtSlider, lv_color_hex(0xB0EF59), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_backlinghtSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_backlinghtSlider, set_enev, LV_EVENT_CLICKED, NULL);

    ui_Button8 = lv_btn_create(ui_menupage);
    lv_obj_set_width(ui_Button8, 63);
    lv_obj_set_height(ui_Button8, 33);
    lv_obj_set_x(ui_Button8, 73);
    lv_obj_set_y(ui_Button8, 58);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0x131510), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label32 = lv_label_create(ui_menupage);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);  /// 1
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT); /// 1
    lv_obj_set_x(ui_Label32, 74);
    lv_obj_set_y(ui_Label32, 57);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label32, &ui_font_return, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
}
